### ISSUE TITLE
可以翻译 点击保存不能自动写入当前文件 也不能写入国际化 react umi4.0项目 vscode版本 1.85.1

### ISSUE THREAD

**Issue by 13621272512** [dbfu/easy-i18n-helper#1]
![image](https://github.com/dbfu/easy-i18n-helper/assets/85733170/fc723992-4e4a-4945-8683-f8c2afc3f458)

**Comment by 13621272512** [comment]
![image](https://github.com/dbfu/easy-i18n-helper/assets/85733170/6a777f9c-88c4-48ad-bed8-8a981a91248f)
右上角这个保存不能自动写入

**Comment by dbfu** [comment]
好的，我检查一下。

**Comment by dbfu** [comment]
你好！本地文件生成了吗？

**Comment by dbfu** [comment]
麻烦把文件夹路径配置发一下

**Comment by 13621272512** [comment]
![image](https://github.com/dbfu/easy-i18n-helper/assets/85733170/3da6d503-edb4-4c66-8284-b5bc20630ea7)

**Comment by dbfu** [comment]
我看你项目里已经有了en-US.ts和zh-CN.ts文件了，能把内容截图看下吗？我猜测可能是以前的文件内容导致的。

**Comment by 13621272512** [comment]
![image](https://github.com/dbfu/easy-i18n-helper/assets/85733170/b7b5fec4-be46-4b3a-8c95-639914ba3462)
![image](https://github.com/dbfu/easy-i18n-helper/assets/85733170/1225229e-15f4-4e37-afb9-b659bf4b3495)
跟本地文件会有关系吗

**Comment by dbfu** [comment]
![image](https://github.com/dbfu/easy-i18n-helper/assets/32224358/234ae68b-f6ab-444e-a89d-377b491a6ee5)
配置路径的时候，要把这个带上，因为你src上面还有一级。

**Comment by 13621272512** [comment]
确实可以了  感谢大佬

**Comment by dbfu** [comment]
> 确实可以了 感谢大佬

好的，不用谢。
